### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by wzxiaobai** [CHENJIAR3/MCMA#1]
Thank you very much for your research, please kindly share the processed data set and test set, or open source data processing code

**Comment by CHENJIAR3** [comment]
All datasets used in this study are openly available. PTB-XL:\url{https://physionet.org/content/ptb-xl/1.0.3/}, CPSC-2018:\url{http://2018.icbeb.org/Challenge.html}, CODE-test:\url{https://zenodo.org/records/3765780}. I did not take any signal preprocessing steps, just splitting ECG signals from PTB-XL and CPSC-2018 into lengths of 1024. The processed dataset is slightly large, and I need to find a way to share it; I will get back to you.

**Comment by CHENJIAR3** [comment]
You can download these datasets with **Baidu Netdisk**: https://pan.baidu.com/s/1yycZodJyFAG95D_O6_jA_Q?pwd=MCMA 

If you have any question, please contact me.
